# Generated by Django 5.1.3 on 2024-12-19 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID владельца'),
        ),
        migrations.AddField(
            model_name='floor',
            name='parking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking', verbose_name='ID парковки'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='floor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.floor', verbose_name='ID этажа'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='parking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking', verbose_name='ID парковки'),
        ),
        migrations.AddField(
            model_name='parkingmetrostations',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking', verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='parkingmetrostations',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.metrostations', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='metrostations',
            name='parkings',
            field=models.ManyToManyField(related_name='parking', through='parking.ParkingMetroStations', to='parking.parking', verbose_name='Парковка'),
        ),
    ]
