# Generated by Django 5.1.3 on 2024-12-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parking_lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot', verbose_name='ID парковочного места'),
        ),
    ]
